### ISSUE TITLE
Add coordinate to soil_compositions

### ISSUE THREAD

**Issue by Canis1219** [AgroScience-Team/field-and-crops#102]
Добавить координату к soil_compositions

- [x] Изучить, какой тип данных в postgis подойдёт для указания единичной точки
- [x]  Не менять апи. Сделать так, чтобы пока проставлялся произвольная координата от контура,к которому относится замер. Поле должно быть not null

**Comment by KABOPOK** [comment]
есть 2 варианта использовать GEOGRAPHY или GEOMETRY. 
GEOMETRY использует плоскую систему координат
GEOGRAPHY использует  /круглую-земли/ систему координат, что делает его более точным.
Но с измерением расстояния и пространственный анализом лушче(бытсрее) справляется  GEOMETRY. 
GEOGRAPHY более сложный способ хранения, его можно использовать если нам важно учесть кривизну земли. 
Учитывая, что у нас выделяемые территории не такие большие, то потери точности не будут значительными, можно использовать GEOMETRY
